# Generated by Django 3.2.7 on 2021-09-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='back_end_dev',
            new_name='back_End_Dev',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='front_end_dev',
            new_name='front_End_Dev',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='full_stack_dev',
            new_name='full_Stack_Dev',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='product_owner',
            new_name='product_Owner',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='project_manager',
            new_name='project_Manager',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='qa_dev',
            new_name='qA_Dev',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='qa_lead',
            new_name='qA_Lead',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_lead',
            new_name='team_Lead',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ui_designer',
            new_name='uI_designer',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ux_designer',
            new_name='uX_Designer',
        ),
    ]
