# Generated by Django 3.2.7 on 2021-09-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_date_created'),
        ('projects', '0002_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ticket'),
        ),
    ]
