# Generated by Django 3.2.7 on 2021-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtrackinguser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
